- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
1. Better instructions for KeyVault creation
2. Include D1, D1_v2, DS1, DS1_v2 images
3. Set max length for hostnames to 8 characters
4. Remove subscriptionId parameter
> Update to Template

- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- nested/clusternode.json
- nested/openshiftdeploy.json
- scripts/deployOpenShift.sh
- scripts/masterPrep.sh
- scripts/nodePrep.sh
Update Templates and Scripts
1. Allow HA mode for Masters
2. Add Infra Nodes
3. Use Azure Storage for Registry
4. Enable Azure for Cloud Provider
5. Create Storage Account for Persistent Storage
6. Create generic storage class
7. Selectable sizes for Docker volume
8. Updated Readme to reflect all changes
9. Updated Parameters files to reflect new parameters
> Azure integration

- CHANGELOG.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
This should take care of https://github.com/Microsoft/openshift-origin/issues/30, https://github.com/Microsoft/openshift-origin/issues/31, https://github.com/Microsoft/openshift-origin/issues/20.
@haroldwongms - please review and merge.
Thanks to @ivanthelad for pointing this out!
> Updates to allowed master count

- README.md
Reflect in the README changes from eb76ed526933b4beac2ea14c11a48ab577c9c533
> Change possible values for Masters VMs count

- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- nested/openshiftdeploy.json
Change encoding of affected files from UTF-8 BOM to UTF-8
> Change encoding to UTF-8

- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- nested/openshiftdeploy.json
As origin officially made the switch, let's use nip.io too.
See https://github.com/openshift/origin/pull/13023
> Add support for nip.io instead of xip.io

- scripts/deployOpenShift.sh
Update to set git clone to specific release-3.6 branch.
> set git clone to specific branch

- CHANGELOG.md
- README.md
- azuredeploy.json
Update Documentation to reference release-3.6 branch
> Release 3 6 Update

- azuredeploy.json
- scripts/deployOpenShift.sh
- scripts/masterPrep.sh
- PVC doesn't work without providing Azure location
- Clone specific version of openshift-ansible repository (release-3.6) instead of master branch which is not stable (guidelines from openshift-ansible authors)
> Add location as it's mandatory for StorageClass

- scripts/deployOpenShift.sh
Add missing playbook for configuration of cockpit
> Add playbook for cockpit

- README.md
- scripts/deployOpenShift.sh
- scripts/masterPrep.sh
Fix issues associated with enabling metrics and logging.  Also update README with more information on metrics and logging.
> Metrics and Logging fixes

- azuredeploy.json
- nested/clusternode.json
- scripts/deployOpenShift.sh
> Fix release-3.6 branch

- CHANGELOG.md
- README.md
- scripts/deployOpenShift.sh
Apply fixes to address installation of Service catalog and Ansible Service Broker (template broker)
> Update to fix issues with Service Catalog

- scripts/deployOpenShift.sh
Added flag "--overwrite=true" to avoid deployment failure if label exists
> Added flag "--overwrite=true"

- CHANGELOG.md
- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- nested/openshiftdeploy.json
- scripts/deployOpenShift.sh
- scripts/masterPrep.sh
- scripts/nodePrep.sh
OpenShift Origin 3.7 for Azure Stack
> Azurestack release 3.7

- README.md
- azuredeploy.json
- azuredeploy.parameters.sample.local.json
- nested/clusternode.json
- nested/openshiftdeploy.json
- scripts/masterPrep.sh
- scripts/nodePrep.sh
Update templates to deploy non LVM image.  Update documentation
> Stack37update

- scripts/deployOpenShift.sh
Add playbook to check for dns hostname resolution before installing OpenShift
> Scriptupdate

- CHANGELOG.md
- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- scripts/deployOpenShift.sh
Support non-HA model with 1 master.
Support for 1, 2, or 3 infra.
> Singlemaster

- azuredeploy.json
@haroldwongms - please take a look and merge. Thanks!
> Correct misformed output (missing space)

- CHANGELOG.md
- README.md
- azuredeploy.json
- azuredeploy.parameters.json
- azuredeploy.parameters.sample.local.json
- scripts/deployOpenShift.sh
also include DNS hostname resolution check.
Bring inline with current master branch as of 5/5/18.
> Introduce single master option

- CHANGELOG.md
- README.md
- azuredeploy.json
- scripts/deployOpenShift.sh
- scripts/masterPrep.sh
- scripts/nodePrep.sh
Apply fix for NetworkManager changes in CentOS 7.5
Cleanup minor items
Add additional comments
> release-3.9update

- CHANGELOG.md
- azuredeploy.json
- scripts/deployOpenShift.sh
Switch to CentOS 7.5 from 7.4
update integrated install to setup Azure Cloud Provider on masters
> Update master branch

- README.md
Following https://github.com/Microsoft/openshift-container-platform/pull/133, I applied the same cleanup to the OpenShift Origin project :-)
> Docs: Convert Azure Deploy Parameters into a table
